project:
  name: quickstart-tableau-awsdata
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  tableau-aws:
    parameters:
      AvailabilityZones: $[alfred_getaz_2]
      BastionAMIOS: Amazon-Linux-HVM
      BastionBanner: https://aws-quickstart.s3.amazonaws.com/quickstart-tableau-awsdata/submodules/quickstart-linux-bastion/scripts/banner_message.txt
      BastionInboundCIDR: 10.0.0.0/16
      BastionInstanceType: t2.micro
      ContentAdminPassword: $[alfred_genpass_16]
      ContentAdminUser: admin
      DatasetS3BucketName: aws-quickstart-datasets
      DatasetS3KeyPrefix: tableau-awsdata/synthetic-store-sales/v1/
      DatasetS3Region: us-east-1
      DomainDNSName: example.com
      HostedZoneName: <NONE>
      KeyPairName: $[alfred_getkeypair]
      LoadDataset: 'true'
      QSS3BucketName: $[taskcat_autobucket]
      RDGWAdminPassword: $[alfred_genpass_16]
      RDGWAdminUser: admin
      RDGWInboundCIDR: 10.0.0.0/16
      RDGWInstanceType: t2.large
      RDSAllocatedStorage: '5'
      RDSDatabaseName: quickstart
      RDSDatabasePort: '5432'
      RDSInboundCIDR: 10.0.0.0/16
      RDSInstanceClass: db.t2.large
      RDSInstanceIdentifier: quickstart-tableau-awsdata
      RDSMultiAZ: 'true'
      RDSPassword: $[alfred_genpass_16]
      RDSUsername: postgres
      RedshiftDatabaseName: quickstart
      RedshiftDatabasePort: '5439'
      RedshiftInboundCIDR: 10.0.0.0/16
      RedshiftNodeType: dc1.large
      RedshiftNumberOfNodes: '2'
      RedshiftPassword: $[alfred_genpass_16]
      RedshiftUsername: redshift
      RegCity: TestCity
      RegCompany: TestCompany
      RegCountry: TestCountry
      RegDepartment: TestDepartment
      RegEmail: test@example.com
      RegFirstName: TestFirstName
      RegIndustry: TestIndustry
      RegLastName: TestLastName
      RegPhone: TestPhone
      RegState: TestState
      RegTitle: TestTitle
      RegZip: TestZip
      SqlWorkerInstanceType: t2.micro
      TableauServerInboundCIDR: 10.0.0.0/16
      TableauServerLicenseKey: ''
      VPCDefinition: QuickstartDefault
    regions:
    - us-west-2
    s3_bucket: ''
    template: templates/tableau-awsdata-master.template
  tableau-no-dataset:
    parameters:
      AvailabilityZones: $[alfred_getaz_2]
      BastionAMIOS: Amazon-Linux-HVM
      BastionBanner: https://aws-quickstart.s3.amazonaws.com/quickstart-tableau-awsdata/submodules/quickstart-linux-bastion/scripts/banner_message.txt
      BastionInboundCIDR: 10.0.0.0/16
      BastionInstanceType: t2.micro
      ContentAdminPassword: $[alfred_genpass_16]
      ContentAdminUser: admin
      DatasetS3BucketName: aws-quickstart-datasets
      DatasetS3KeyPrefix: tableau-awsdata/synthetic-store-sales/v1/
      DatasetS3Region: us-east-1
      DomainDNSName: example.com
      HostedZoneName: <NONE>
      KeyPairName: $[alfred_getkeypair]
      LoadDataset: 'false'
      QSS3BucketName: $[taskcat_autobucket]
      RDGWAdminPassword: $[alfred_genpass_16]
      RDGWAdminUser: admin
      RDGWInboundCIDR: 10.0.0.0/16
      RDGWInstanceType: t2.large
      RDSAllocatedStorage: '5'
      RDSDatabaseName: quickstart
      RDSDatabasePort: '5432'
      RDSInboundCIDR: 10.0.0.0/16
      RDSInstanceClass: db.t2.large
      RDSInstanceIdentifier: quickstart-tableau-awsdata
      RDSMultiAZ: 'true'
      RDSPassword: $[alfred_genpass_16]
      RDSUsername: postgres
      RedshiftDatabaseName: quickstart
      RedshiftDatabasePort: '5439'
      RedshiftInboundCIDR: 10.0.0.0/16
      RedshiftNodeType: dc1.large
      RedshiftNumberOfNodes: '2'
      RedshiftPassword: $[alfred_genpass_16]
      RedshiftUsername: redshift
      RegCity: TestCity
      RegCompany: TestCompany
      RegCountry: TestCountry
      RegDepartment: TestDepartment
      RegEmail: test@example.com
      RegFirstName: TestFirstName
      RegIndustry: TestIndustry
      RegLastName: TestLastName
      RegPhone: TestPhone
      RegState: TestState
      RegTitle: TestTitle
      RegZip: TestZip
      SqlWorkerInstanceType: t2.micro
      TableauServerInboundCIDR: 10.0.0.0/16
      TableauServerLicenseKey: ''
      VPCDefinition: QuickstartDefault
    regions:
    - us-east-2
    s3_bucket: ''
    template: templates/tableau-awsdata-master.template
